# =============================================
# Makefile for (amazing) Weiming Beamer Presentation
# ===========================================

# Name of your main .tex file (without the extension)
PROJECT = main

# Define the compiler to guarantee pdfLaTeX is used
TEX = pdflatex

# Flags to stop compilation immediately if an error is found
TEXFLAGS = -interaction=nonstopmode -halt-on-error

# Default target when you just type 'make' (OpenBSD: 'gmake')
all: $(PROJECT).pdf

# Compile the document twice to ensure progress bars and references are updated
$(PROJECT).pdf: $(PROJECT).tex beamerthemeweiming.sty
	$(TEX) $(TEXFLAGS) $<
	$(TEX) $(TEXFLAGS) $<

# 'make clean' removes all the clutter generated by LaTeX
clean:
	rm -f *.aux *.log *.nav *.out *.snm *.toc *.vrb

# 'make distclean' removes the clutter PLUS the final PDF
distclean: clean
	rm -f $(PROJECT).pdf

# Tell 'make' that these aren't actual files, just commands
.PHONY: all clean distclean
